<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>cobalogindatabase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c9daf988-7c58-4af1-9f48-4e95457ee0dc</testSuiteGuid>
   <testCaseLink>
      <guid>7b03e3eb-e91c-4625-95fb-4e84490db323</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/databasetestbro/database</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>988dbea5-6f40-4689-95e3-310ac10e7857</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataBro</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>988dbea5-6f40-4689-95e3-310ac10e7857</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>356936a0-7b6d-4e0e-9e59-55b50ba83dd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>988dbea5-6f40-4689-95e3-310ac10e7857</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>f2bfc7b0-0791-4da0-9315-b59b88c4cb95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88455285-5d98-4253-9a1e-69daa7695e56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24c527bb-8246-432e-97f2-65823bda2aa1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
