<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kategori_css-15kuy91</name>
   <tag></tag>
   <elementGuidId>2da07412-0c21-429f-8466-18a07483446e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.css-15kuy91</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>62851640-952b-4072-86ab-ad5b190a469f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15kuy91</value>
      <webElementGuid>b9de4770-7962-4f54-957b-8c8a0240fa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1s8dqy5 e90swyx2&quot;]/div[@class=&quot;css-1brt7yz&quot;]/div[@class=&quot;css-1i12xq8&quot;]/i[@class=&quot;css-15kuy91&quot;]</value>
      <webElementGuid>1a6b7edd-f859-455c-b0e7-1e94e92d9685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div/i</value>
      <webElementGuid>63da4d54-bab0-4738-a4a5-80f4e71a7280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>78eef41a-b60c-4bed-b690-a618d92191fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
