<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Logout</name>
   <tag></tag>
   <elementGuidId>fa32923b-21dd-4ec3-acc1-e4719bacebed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vm__white-header-dweb']/section/header/div[3]/div/div/div[2]/div/span[6]/div/div[2]/div/div/div/div/ul[2]/li[6]/a/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>acfbc0ea-be2f-495d-87a6-4d452e175065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text bl-text--body-default</value>
      <webElementGuid>b7aad73c-7dbd-4d2b-b6f1-e7a0318b9096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Logout
          </value>
      <webElementGuid>fd64a9e3-4ae6-4f46-a137-676de4fb2859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vm__white-header-dweb&quot;)/section[@class=&quot;bl-section sigil-header&quot;]/header[@class=&quot;c-header-v2&quot;]/div[@class=&quot;sigil-header__main-nav-bar&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-space-between align-items-center&quot;]/div[@class=&quot;bl-flex-item&quot;]/div[@class=&quot;bl-flex-container align-items-center&quot;]/span[@class=&quot;sigil-header__nav&quot;]/div[@class=&quot;bl-popover bl-popover--right bl-popover--active&quot;]/div[@class=&quot;bl-popover__outer&quot;]/div[@class=&quot;bl-popover__inner&quot;]/div[1]/div[1]/div[1]/ul[@class=&quot;bl-list mt-8&quot;]/li[@class=&quot;bl-list-item has-hover&quot;]/a[@class=&quot;bl-list-item__wrapper&quot;]/div[@class=&quot;bl-flex-container align-items-center&quot;]/div[@class=&quot;bl-list-item__title&quot;]/p[@class=&quot;bl-text bl-text--body-default&quot;]</value>
      <webElementGuid>e14d9856-0f9f-4c80-b156-a295425ca08c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vm__white-header-dweb']/section/header/div[3]/div/div/div[2]/div/span[6]/div/div[2]/div/div/div/div/ul[2]/li[6]/a/div/div/p</value>
      <webElementGuid>dfe188ff-626a-428c-9d53-980f71d6aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='erwan yudha'])[1]/following::p[6]</value>
      <webElementGuid>7bf13c3e-011f-438b-bb25-e041b72bcb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua pembelian'])[1]/following::p[9]</value>
      <webElementGuid>aba2aea2-d63f-4bd5-8acb-57306dd87535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/preceding::p[1]</value>
      <webElementGuid>8146a41f-864a-4e8e-8137-6a3e20f59725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[2]/preceding::p[16]</value>
      <webElementGuid>7663ee07-1c92-4a2f-8f1f-f98cbbc8d687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>f8e1c268-f8bb-482b-927d-e7b1bbfb8b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[6]/a/div/div/p</value>
      <webElementGuid>6dcf2f78-2d50-4f0e-bcfc-ed66642ad0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
            Logout
          ' or . = '
            Logout
          ')]</value>
      <webElementGuid>9d20e538-5119-4fe2-9c0d-2f52242400b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
