<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get back to Katalon_user_email</name>
   <tag></tag>
   <elementGuidId>55ca035d-2b66-47fd-b00c-354dc4024a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signin_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5be51e79-9c12-4482-9239-9306edbed298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f71cca4c-ab7d-48a8-8c30-485456fb09e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18209959-38a1-486a-a5be-066ab3a63643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_email</value>
      <webElementGuid>b4072602-4dad-4cba-a256-11c29022e505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin_email</value>
      <webElementGuid>b96ffe31-2908-454e-807f-1bb17e1ffd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f22e2648-3242-43c1-afea-6b7f360935b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_email&quot;)</value>
      <webElementGuid>66870ec6-ec7c-4448-8ee3-84a5fad5e5db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signin_email']</value>
      <webElementGuid>984dfb01-f096-445f-9e21-d7c3db984e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_71538058904']/div[3]/div/form/div/input</value>
      <webElementGuid>94cf8a25-37d1-4d17-a4a7-e4afbd85cadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cbe7b61a-8928-47ff-bef3-e36b17ea514b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'user_email' and @id = 'signin_email' and @placeholder = 'Email']</value>
      <webElementGuid>a761c94e-84ac-43b7-bfb0-cce804182d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
