<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_bapakmubapaku4</name>
   <tag></tag>
   <elementGuidId>cddfda60-4799-43a9-b0fa-f98e40b0260d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div[2]/div[2]/div/ul/li[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55e90bbc-de67-4b75-a7f4-aa500162eddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>xqKM5b</value>
      <webElementGuid>524dd146-3aeb-44a8-b8c5-039d414617db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-username</name>
      <type>Main</type>
      <value>bapakmubapaku4</value>
      <webElementGuid>608d6e8d-5668-428c-9a9a-82b556c0f7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bapakmubapaku4</value>
      <webElementGuid>bba6226f-8c25-4470-bda1-4e013e3bcac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_container&quot;)/div[@class=&quot;zWl5kd&quot;]/div[@class=&quot;DRS7Fe bxPAYd k6Zj8d&quot;]/div[@class=&quot;pwWryf bxPAYd&quot;]/div[@class=&quot;Wxwduf Us7fWe JhUD8d&quot;]/div[@class=&quot;WEQkZc&quot;]/div[@class=&quot;bCAAsb&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]/div[1]/div[@class=&quot;akwVEf OcVpRe&quot;]/div[2]/div[1]/ul[@class=&quot;S9BUjf&quot;]/li[@class=&quot;oMzjQd&quot;]/button[1]</value>
      <webElementGuid>8cb8e971-acff-4683-b90a-b5faf87187a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div[2]/div[2]/div/ul/li[4]/button</value>
      <webElementGuid>35ae96e8-087d-4450-8d33-f43050c8dba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bapakubapakmu749'])[1]/following::button[1]</value>
      <webElementGuid>c41de720-2d4f-47d9-9b5b-41a76b68100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bapakmubapaku91'])[1]/following::button[2]</value>
      <webElementGuid>95a7de24-5851-4f49-9033-a93c75e14c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunakan minimal 8 karakter dengan campuran huruf, angka &amp; simbol'])[1]/preceding::button[1]</value>
      <webElementGuid>73ab304a-a971-4400-8c57-51da55fe35af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan sandi'])[1]/preceding::button[1]</value>
      <webElementGuid>075057f3-1473-4478-898b-394e0d9b12b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bapakmubapaku4']/parent::*</value>
      <webElementGuid>4167fe1d-8d18-4fce-b018-61e281d6a499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>94ff11b5-e42f-4e93-af38-e0dc793f3af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'bapakmubapaku4' or . = 'bapakmubapaku4')]</value>
      <webElementGuid>1635e8e4-a897-4bb2-8176-e806d650accd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
