<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Verifikasi</name>
   <tag></tag>
   <elementGuidId>879d74dc-076f-4572-b874-90e26a9707d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TFAJS-1652928822443']/section/div/div[2]/div/div[2]/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div > div > button.bl-button.bl-button--primary.bl-button--medium.bl-button--block > span.bl-text.bl-text--body-default.bl-text--semi-bold.bl-text--inverse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33915620-e23c-4783-9f63-b6d4d67931dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text bl-text--body-default bl-text--semi-bold bl-text--inverse</value>
      <webElementGuid>6e497323-a09a-41dc-b89c-1b6f34e15eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi</value>
      <webElementGuid>3a85785c-bc7c-4e84-85c8-a4385680aa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TFAJS-1652928822443&quot;)/section[1]/div[@class=&quot;bl-modal p-24&quot;]/div[@class=&quot;bl-modal__wrapper&quot;]/div[@class=&quot;bl-card&quot;]/div[@class=&quot;bl-modal__body&quot;]/div[@class=&quot;p-24&quot;]/div[1]/div[1]/div[1]/button[@class=&quot;bl-button bl-button--primary bl-button--medium bl-button--block&quot;]/span[@class=&quot;bl-text bl-text--body-default bl-text--semi-bold bl-text--inverse&quot;]</value>
      <webElementGuid>070248a0-f4c2-4495-a273-df74fa6dea26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1652928822443']/section/div/div[2]/div/div[2]/div/div/div/div/button/span</value>
      <webElementGuid>407d7b16-77c3-4a7b-b7ac-167805ed0ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim ulang'])[1]/following::span[1]</value>
      <webElementGuid>8a57eaaf-8f9a-4411-8809-1a4f2ff3e2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode rahasia'])[1]/following::span[2]</value>
      <webElementGuid>5bf46eb5-b361-49ef-b7ca-2bdd4b78d88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi']/parent::*</value>
      <webElementGuid>95519ac5-82e7-4ad9-92a8-3426821236ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button/span</value>
      <webElementGuid>12e6f451-b09b-4b0d-a83c-ca3878021367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Verifikasi' or . = 'Verifikasi')]</value>
      <webElementGuid>b699a9a2-6aef-4fc8-9209-e31195ec29c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
