<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_bambangzalay12345</name>
   <tag></tag>
   <elementGuidId>c74aa114-299d-4c4e-89c7-fb765279ecac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stardust-popover2']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navbar__username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eacd3549-b085-4f22-b9af-af64d21001b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__username</value>
      <webElementGuid>dc7e3d32-2b7a-453a-9381-067ab4078c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bambangzalay12345</value>
      <webElementGuid>29468040-3df0-4314-80dc-0fb3ba83f398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stardust-popover2&quot;)/div[@class=&quot;stardust-popover__target&quot;]/div[@class=&quot;navbar__link--account__container&quot;]/div[@class=&quot;navbar__username&quot;]</value>
      <webElementGuid>9d677626-e8fe-4827-9497-cfa2a10990cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stardust-popover2']/div/div/div[2]</value>
      <webElementGuid>629812fd-3e52-48d2-9e99-e6e0c797dbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::div[6]</value>
      <webElementGuid>433b1f5a-b293-4558-b958-8ede92c6d2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bantuan'])[1]/following::div[10]</value>
      <webElementGuid>1f5dbdb0-ae29-496d-8730-d2d1a5b95c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akun saya'])[1]/preceding::div[3]</value>
      <webElementGuid>79ad0135-22c7-440b-a4c9-4adcc042308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pesanan saya'])[1]/preceding::div[3]</value>
      <webElementGuid>c0b5ad18-509f-4ee2-91fc-70d4beb9c6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bambangzalay12345']/parent::*</value>
      <webElementGuid>6d9fecdf-1883-483a-9e3b-15855bea420e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/div[2]</value>
      <webElementGuid>3fd59460-672c-4ca2-a1f8-fc223ff13b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'bambangzalay12345' or . = 'bambangzalay12345')]</value>
      <webElementGuid>7c80e70e-eba8-4d56-bd7a-0a17f55802b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
