<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Products_hs-image-widget</name>
   <tag></tag>
   <elementGuidId>91037102-c9ec-40b9-b5df-e56827977267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hs-link-header_logo_hs_logo_widget']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d162dcef-387c-4f0b-9dd6-6a7cf4d5e31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=360&amp;name=logo_katalon_text_black.png</value>
      <webElementGuid>05f13aa3-d5d9-4881-a064-8dad641196c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-image-widget </value>
      <webElementGuid>16a1210a-73b6-4f8a-b167-196cd9e24ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>d6984252-e92d-4cfe-a9d6-f806379f304b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Katalon, Inc</value>
      <webElementGuid>e10e8206-c502-4ab4-9f95-48a53cbbc436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Katalon, Inc</value>
      <webElementGuid>fdf42aff-5daa-42c4-bbf1-95f4df86a98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=180&amp;name=logo_katalon_text_black.png 180w, https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=360&amp;name=logo_katalon_text_black.png 360w, https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=540&amp;name=logo_katalon_text_black.png 540w, https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=720&amp;name=logo_katalon_text_black.png 720w, https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=900&amp;name=logo_katalon_text_black.png 900w, https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=1080&amp;name=logo_katalon_text_black.png 1080w</value>
      <webElementGuid>c48fe03b-baf1-4f6a-98eb-22890aa36439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 360px) 100vw, 360px</value>
      <webElementGuid>d0315ea0-48c4-4d4c-8e94-2b63437fbff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40px</value>
      <webElementGuid>6dd96ffe-0e9a-48f9-a6cd-20b4e700063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs-link-header_logo_hs_logo_widget&quot;)/img[@class=&quot;hs-image-widget&quot;]</value>
      <webElementGuid>dc372265-ab77-488d-b2a2-20ea4859513c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='hs-link-header_logo_hs_logo_widget']/img</value>
      <webElementGuid>eddabd71-a74a-471f-9669-d907c34b0246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Katalon, Inc']</value>
      <webElementGuid>79c39cee-1a04-4e07-af1d-6a8b976d8bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>2acf5788-e66c-49c1-89df-146b6be3cebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon.com/hs-fs/hubfs/raw_assets/public/Katalon_December2021/images/logo_katalon_text_black.png?width=360&amp;name=logo_katalon_text_black.png' and @alt = 'Katalon, Inc' and @title = 'Katalon, Inc']</value>
      <webElementGuid>b9872c51-7949-4971-8d02-d34004770e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
