<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ibox</name>
   <tag></tag>
   <elementGuidId>3d4f6009-e8e5-4fd8-a86e-5b02d40ad0dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.shopee-searchbar-hints__entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopee-searchbar-listbox']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>806e4426-8b61-4260-9cbf-9888306d45b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-searchbar-hints__entry</value>
      <webElementGuid>f26a396f-d35e-400f-bf1a-48d9ed93fa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>561d1ef2-6b26-4686-9b11-7fd5f0fb526f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?keyword=ibox&amp;trackingId=searchhint-1652754163-3bcf9383-d588-11ec-b463-1ed341e191ac</value>
      <webElementGuid>e6105fce-dd78-4522-81bb-5e5d880956fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ibox</value>
      <webElementGuid>02d212a8-79f9-4408-9c1f-7265986a396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopee-searchbar-listbox&quot;)/a[@class=&quot;shopee-searchbar-hints__entry&quot;]</value>
      <webElementGuid>12490ca2-b44c-4144-9e58-f502ecab5ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopee-searchbar-listbox']/a[2]</value>
      <webElementGuid>58494abd-e738-4a93-936a-6a88c5f16b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ibox'])[1]/following::a[1]</value>
      <webElementGuid>fd876b36-bd0e-4620-8453-a0bf26685c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ibox'])[3]/preceding::a[1]</value>
      <webElementGuid>db5fe407-1304-40bb-b5c7-f555f8c39866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?keyword=ibox&amp;trackingId=searchhint-1652754163-3bcf9383-d588-11ec-b463-1ed341e191ac')]</value>
      <webElementGuid>a5cac810-6041-4060-a9c4-11576a5fe910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>eae06c19-f2b5-4547-b695-5351a787c484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?keyword=ibox&amp;trackingId=searchhint-1652754163-3bcf9383-d588-11ec-b463-1ed341e191ac' and (text() = 'ibox' or . = 'ibox')]</value>
      <webElementGuid>0ee40fe4-b6d3-47e9-ba8e-f104f22c006a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
